### PR TITLE
Pythonnet 303

### PR DESCRIPTION
**Pull request by sanzoghenzo**
### What does this implement/fix? Explain your changes.

Update to python.Net 3.0.3 (latest release)

### Does this close any currently open issues?

No

### Any other comments?

I reduced the modifications needed and changed pyRevit source code to only use public classes and methods.
We could even drop this and directly use the nuget package, since a single compiled assembly can be used for multiple python version by setting the python dll path.

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by jmcouffin** [comment]
Let me know when you feel it is ready to go.
@sanzoghenzo

**Comment by dosymep** [comment]
@sanzoghenzo 
I think it’s better to pull not the latest version, but the latest version by [tag](https://github.com/pythonnet/pythonnet/releases/tag/v3.0.3).

**Comment by sanzoghenzo** [comment]
> @sanzoghenzo I think it’s better to pull not the latest version, but the latest version by [tag](https://github.com/pythonnet/pythonnet/releases/tag/v3.0.3).

I did exactly that, I forked pythonnet from the 3.0.3 release commit and added the namespace editing on top of that

**Comment by dosymep** [comment]
@sanzoghenzo but in PR latest commit is not *Release 3.0.3*

your last commit: https://github.com/pythonnet/pythonnet/commit/1a4ada7b91619728fe2cd4866a635406c5c06988
version 3.0.3 commit: https://github.com/pythonnet/pythonnet/commit/0a5a63ccc4ee1e104ab0aae75ede8aa3441a3481

**Comment by sanzoghenzo** [comment]
> @sanzoghenzo but in PR latest commit is not _Release 3.0.3_
> 
> your last commit: [pythonnet@1a4ada7](https://github.com/pythonnet/pythonnet/commit/1a4ada7b91619728fe2cd4866a635406c5c06988) version 3.0.3 commit: [pythonnet@0a5a63c](https://github.com/pythonnet/pythonnet/commit/0a5a63ccc4ee1e104ab0aae75ede8aa3441a3481)

The commit history is in increasing order, check the last two elements 😉  (I made the same mistake while checking things after your first message)

**Comment by dosymep** [comment]
@sanzoghenzo oh okay :)

**Pull request closed without merging**
